### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Studiedlist** [niuiic/translate.nvim#3]
It would be useful to be able to configure time to wait for response. Sometimes there are connection lags, and request (or response) never reaches destination or do it very slowly, so translation is stuck for some time.

As I see it, there are two possible solutions:
- add command to cancel current translate task
- add ability to set maximum waiting time. If time exceeded, task is canceled automatically

**Comment by niuiic** [comment]
Check the lastest commit, unfinished previous job will be overrided now.

**Comment by Studiedlist** [comment]
Thanks for blazingly fast solution, it should do it
