### ISSUE TITLE
no ‘core’ deps

### ISSUE THREAD

**Issue by cxwx** [niuiic/translate.nvim#5]
/lazy/translate.nvim/lua/translate/init.lua:1: module 'core' not found:
	no field package.preload['core']
cache_loader: module core not found
cache_loader_lib: module core not found

**Comment by niuiic** [comment]
Did you check the plugin dependencies [here](https://github.com/niuiic/translate.nvim?tab=readme-ov-file#dependencies).

**Comment by cxwx** [comment]
got it
